server:
  port: 90
spring:
  application:
    name: auth-uaa
  cloud:
    nacos:
      discovery:
        ip: localhost:8848
        username: nacos
        password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/base_auth?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  output:
    ansi:
      enabled: always
#mybatis 配置
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
#logging:
 # config: ./logback.xml   //xml的配置方式走日志
logging:
  level:
    root: info
    #控制台输出
 # pattern:
  #  console:    #不需要格式 默认出书彩色  可以自定义
    #外部文件输出
    sql: info
  file:
    name: auth-uaa.log
    path: /Users/zero/Desktop/log
  logback:
    rollingpolicy:
      max-file-size: 1MB    # 指定文件最大规格
      file-name-pattern: /users/zero/Desktop/log/auth_%d{yyyy-MM-dd}_%i.log




